In [27]:
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
import re, string, unicodedata
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from sklearn.model_selection import train_test_split
from transformers import BertModel, BertTokenizer
import torch
from torch.utils.data import DataLoader
from torch.utils.data import Dataset
from datasets import Dataset, DatasetDict
from transformers import Trainer, TrainingArguments, BertForSequenceClassification
from sklearn.metrics import accuracy_score, f1_score, recall_score

In [2]:
df_new = pd.read_csv('preprocessed_data_news.csv')

In [3]:
df_new["text"] = df_new["text"].astype(str)

In [4]:
print(df_new[df_new["text"].isnull()])

Empty DataFrame
Columns: [Unnamed: 0, title, text, label]
Index: []

In [9]:
df_new

,Unnamed: 0,title,text,label
0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,comment expect barack obama member fyf fukyofl...,1
1,1,NaN,post vote hillari alreadi,1
2,2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,demonstr gather last night exercis constitut p...,1
3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",dozen polit activ pastor came privat dinner fr...,0
4,4,SATAN 2: Russia unvelis an image of its terrif...,rs sarmat missil dub satan replac ss fli mile ...,1
...,...,...,...,...
495,495,Trump ordered to give deposition in Washington...,washington reuter washington judg order republ...,0
496,496,Obama’s Race War Makes Its Way To His Hometown...,insanewatch protest erupt chicago tuesday nigh...,1
497,497,FACTBOX: About 6.1 million without power in U....,reuter power outag hurrican irma drop million ...,0
498,498,OOPS! ABSOLUTELY NO ONE SHOWED UP For NYC Debu...,nordstrom yesterday salesperson ask teenag dau...,1
499,499,"Russia warns Iraq, Kurds not to destabilize Mi...",moscow reuter russia wednesday warn iraq kurd ...,0

In [12]:
train_texts, val_texts, train_labels, val_labels = train_test_split(
    df_new['text'].tolist(),
    df_new['label'].tolist(),
    test_size=0.2,
    stratify=df_new['label'],
    random_state=42
)

In [13]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

In [14]:
train_encodings = tokenizer(train_texts, truncation=True, padding=True, max_length=256)
val_encodings = tokenizer(val_texts, truncation=True, padding=True, max_length=256)

In [15]:
print(train_encodings.keys())  # ['input_ids', 'token_type_ids', 'attention_mask']
print(train_encodings['input_ids'][0])  # Token ID untuk teks pertama

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])
[101, 2940, 8486, 7207, 4012, 24759, 2594, 2450, 2448, 4175, 3089, 2215, 14955, 4183, 4132, 4906, 4744, 2121, 6178, 27467, 2094, 2579, 2843, 3684, 5082, 2397, 2272, 2105, 9388, 4360, 2290, 5020, 21934, 24759, 11969, 5507, 19646, 4218, 14175, 6305, 2424, 2995, 3410, 12010, 2157, 2802, 2088, 2860, 10222, 2272, 7207, 23408, 4747, 4904, 12010, 2157, 2843, 4190, 25090, 2213, 12087, 2034, 3129, 4190, 6305, 2072, 2348, 2036, 21934, 24759, 8246, 23689, 6590, 3089, 14955, 28775, 3198, 2425, 3021, 7207, 2293, 14955, 28775, 2387, 2190, 4012, 21572, 15630, 2051, 11253, 2522, 9236, 2940, 8486, 14955, 28775, 2755, 2056, 3198, 2425, 2292, 2693, 6232, 4091, 2940, 8486, 2272, 2105, 5138, 9388, 4360, 2290, 5020, 2093, 2095, 3283, 2028, 3357, 2146, 2010, 29469, 2490, 2239, 14570, 28667, 7416, 2615, 13594, 2102, 2012, 6528, 2102, 20774, 5637, 2157, 3031, 25204, 2754, 4189, 2360, 2302, 7207, 3947, 3795, 2358, 26549, 23296, 5020, 5637, 11690, 20377, 10288, 2226, 9099, 6914, 2094, 12010, 21877, 7361, 2140, 2052, 10838, 3435, 2627, 7367, 6299, 2095, 2052, 3131, 2110, 2464, 2651, 3795, 3003, 2358, 26549, 23296, 2540, 3947, 3131, 3842, 2529, 2157, 2473, 24501, 4747, 4904, 4424, 16865, 5907, 8909, 4765, 2060, 9148, 2015, 2124, 4895, 8093, 2278, 5637, 2157, 24501, 4747, 4904, 25204, 3820, 3005, 4433, 3696, 7207, 14105, 6254, 2905, 4895, 8093, 2278, 24501, 4747, 4904, 28887, 3424, 2140, 18259, 2102, 6819, 9890, 12273, 5860, 20026, 2378, 4895, 5337, 28667, 8649, 2078, 5637, 2157, 2112, 25204, 2529, 2157, 6939, 20464, 27028, 5637, 2157, 13675, 10383, 2094, 2211, 2306, 2110, 18280, 10938, 2028, 102]

In [16]:
class NewsDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels
    
    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item
    
    def __len__(self):
        return len(self.labels)

In [17]:
train_dataset = NewsDataset(train_encodings, train_labels)
val_dataset = NewsDataset(val_encodings, val_labels)

In [18]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=2)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [20]:
training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    warmup_steps=10,
    weight_decay=0.01,
    evaluation_strategy='epoch',
    save_strategy='epoch',
    save_total_limit=1,               
    logging_dir='./logs',
    logging_steps=10,
    load_best_model_at_end=True
)

In [21]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset
)

In [22]:
trainer.train()

TrainOutput(global_step=150, training_loss=0.4402747337023417, metrics={'train_runtime': 1347.2181, 'train_samples_per_second': 0.891, 'train_steps_per_second': 0.111, 'total_flos': 157866633216000.0, 'train_loss': 0.4402747337023417, 'epoch': 3.0})

In [23]:
trainer.evaluate()

{'eval_loss': 0.27908098697662354,
 'eval_runtime': 27.3401,
 'eval_samples_per_second': 3.658,
 'eval_steps_per_second': 0.475,
 'epoch': 3.0}

In [28]:
def compute_metrics(p):
    predictions, labels = p
    preds = predictions.argmax(axis=1)
    
    accuracy = accuracy_score(labels, preds)
    f1 = f1_score(labels, preds)
    recall = recall_score(labels, preds)
    
    return {
        'accuracy': accuracy,
        'f1': f1,
        'recall': recall
    }

trainer = Trainer(
    model=model,                          # Model yang sudah dilatih
    args=training_args,                   # Training arguments
    train_dataset=train_dataset,          # Dataset untuk training
    eval_dataset=val_dataset,             # Dataset untuk validasi
    compute_metrics=compute_metrics       # Menghitung metrik evaluasi
)

# Evaluasi hasil model
eval_result = trainer.evaluate()

# Menampilkan metrik
print(eval_result)

{'eval_loss': 0.27908098697662354, 'eval_model_preparation_time': 0.0127, 'eval_accuracy': 0.9, 'eval_f1': 0.9107142857142856, 'eval_recall': 0.9272727272727272, 'eval_runtime': 26.718, 'eval_samples_per_second': 3.743, 'eval_steps_per_second': 0.487}

In [29]:
# Simpan model
model.save_pretrained("./saved_model")

# Simpan tokenizer
tokenizer.save_pretrained("./saved_model")

('./saved_model\\tokenizer_config.json',
 './saved_model\\special_tokens_map.json',
 './saved_model\\vocab.txt',
 './saved_model\\added_tokens.json')